import os
import requests
import json

SYMBOL = "XAUTUSD"
BASE_URL = "https://api.india.delta.exchange"


def fetch_ticker_price():
    """Fetches real-time price from Delta's public API (No auth/IP restriction)."""
    try:
        endpoint = f"/v2/tickers/{SYMBOL}"
        res = requests.get(BASE_URL + endpoint, timeout=10)
        if res.status_code == 200:
            return float(res.json().get("result", {}).get("close", 0.0))
    except Exception:
        pass
    return 0.0


def fetch_local_state():
    """Reads live position state generated by your Oracle VM."""
    if os.path.exists("xautusd_state.json"):
        try:
            with open("xautusd_state.json", "r") as f:
                return json.load(f)
        except Exception:
            pass
    return {}


def build_dashboard():
    current_price = fetch_ticker_price()
    state = fetch_local_state()

    position = state.get("position", {
        "direction": "FLAT",
        "size": 0,
        "entry_price": 0.0,
        "stop_loss": 0.0,
        "unrealized_pnl": 0.0
    })

    balance = float(state.get("balance", 0.0))
    trades = state.get("trades", [])

    total_pnl = sum(t.get("pnl", 0.0) for t in trades)
    winning_trades = sum(1 for t in trades if t.get("pnl", 0.0) > 0)
    losing_trades = sum(1 for t in trades if t.get("pnl", 0.0) < 0)
    total_trades = len(trades)
    win_rate = (winning_trades / total_trades * 100) if total_trades > 0 else 0.0

    return {
        "success": True,
        "bot_running": True,
        "current_price": current_price,
        "balance": balance,
        "total_pnl": total_pnl,
        "today_pnl": total_pnl,
        "position": position,
        "statistics": {
            "total_trades": total_trades,
            "winning_trades": winning_trades,
            "losing_trades": losing_trades,
            "win_rate": round(win_rate, 1)
        },
        "trades": trades
    }


if __name__ == "__main__":
    print(json.dumps(build_dashboard(), indent=2))
